### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by SangeloDev** [iBuyMountainDew/mpm#3]
After installation, I get this error when running mvm -V:

Error: Could not find or load main class C:\Users\my-username\.mpm\

But this file doesn't exist there. So how can I fix this?

**Comment by wijiler** [comment]
if its linux only as it says in the description it should be pathed $HOME/*username*/my-username.mpm
or  ~/*username*/my-username.mpm

**Comment by wijiler** [comment]
and if you do use linux make sure your path and your java is configured right
